name: Publish New Release - Scheduled
on:
   schedule:
    # At 09:00 on Monday.
     - cron: "0 9 * * 1"
jobs:
  ci:
    uses: ./.github/workflows/node.js.yml
    secrets: inherit

  publish:
    needs: [ci]
    uses: ./.github/workflows/lerna-publish.yml
    secrets: inherit
